### PR TITLE
fix: resolve errors with latest tree-sitter CLI

### PR DESCRIPTION
**Pull request by clason**
This PR adapts to breaking changes in tree-sitter CLI that prevents this parser from being generated on `master` (and hence the upcoming release): The "trick" of wrapping an anonymous node into a single `choice` or `seq` no longer works as of https://github.com/tree-sitter/tree-sitter/pull/2577 since the wrapped anonymous nodes are no longer exposed to queries.

Solution: Drop unnecessary `choice` and use named node in query. Don't wrap single nodes in `seq` in the `paired` function.

@amaanq

### CODE REVIEW

**Comment by clason** [comment]
Fixed the lint failure (hopefully); not sure how these changes lead to the test failures?

**Comment by clason** [comment]
@hankthetank27 Fixed the tests (and hopefully the lint failure).

**Comment by hankthetank27** [comment]
@clason fantastic! Looks good. Thanks for this.

**Comment by clason** [comment]
(Marked as breaking since downstream will need to adapt their queries; since tests don't contain anonymous nodes, I assumed you'd prefer to keep the more explicit tests rather than the queries.)

**Pull request merged**
